<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="MAIN" Id="{3e3f65f9-9d9d-43dd-8626-18157aff0998}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	_station : fbStation;	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_station();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="91" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>