//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainPlcConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainPlcConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All in position ready to start.
        /// </summary>
        public static string ___All_in_position_ready_to_start__ {
            get {
                return ResourceManager.GetString("___All_in_position_ready_to_start__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquired.
        /// </summary>
        public static string ___Aquired__ {
            get {
                return ResourceManager.GetString("___Aquired__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking base position.
        /// </summary>
        public static string ___Checking_base_position__ {
            get {
                return ResourceManager.GetString("___Checking_base_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        public static string ___Components__ {
            get {
                return ResourceManager.GetString("___Components__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentMode.
        /// </summary>
        public static string ___CurrentMode__ {
            get {
                return ResourceManager.GetString("___CurrentMode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string ___Data__ {
            get {
                return ResourceManager.GetString("___Data__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DimensionX.
        /// </summary>
        public static string ___DimensionX__ {
            get {
                return ResourceManager.GetString("___DimensionX__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DimensionY.
        /// </summary>
        public static string ___DimensionY__ {
            get {
                return ResourceManager.GetString("___DimensionY__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DimensionZ.
        /// </summary>
        public static string ___DimensionZ__ {
            get {
                return ResourceManager.GetString("___DimensionZ__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error description.
        /// </summary>
        public static string ___Error_description__ {
            get {
                return ResourceManager.GetString("___Error_description__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gripper.
        /// </summary>
        public static string ___Gripper__ {
            get {
                return ResourceManager.GetString("___Gripper__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal piston.
        /// </summary>
        public static string ___Horizontal_piston__ {
            get {
                return ResourceManager.GetString("___Horizontal_piston__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locker.
        /// </summary>
        public static string ___Locker__ {
            get {
                return ResourceManager.GetString("___Locker__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string ___Max__ {
            get {
                return ResourceManager.GetString("___Max__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure the parameters..
        /// </summary>
        public static string ___Measure_the_parameters___ {
            get {
                return ResourceManager.GetString("___Measure_the_parameters___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string ___Min__ {
            get {
                return ResourceManager.GetString("___Min__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move entity to Failed conveyor.
        /// </summary>
        public static string ___Move_entity_to_Failed_conveyor__ {
            get {
                return ResourceManager.GetString("___Move_entity_to_Failed_conveyor__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move entity to Passed conveyor.
        /// </summary>
        public static string ___Move_entity_to_Passed_conveyor__ {
            get {
                return ResourceManager.GetString("___Move_entity_to_Passed_conveyor__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving everything to ground position.
        /// </summary>
        public static string ___Moving_everything_to_ground_position__ {
            get {
                return ResourceManager.GetString("___Moving_everything_to_ground_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Error.
        /// </summary>
        public static string ___No_Error__ {
            get {
                return ResourceManager.GetString("___No_Error__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select mode.
        /// </summary>
        public static string ___Select_mode__ {
            get {
                return ResourceManager.GetString("___Select_mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step description.
        /// </summary>
        public static string ___Step_description__ {
            get {
                return ResourceManager.GetString("___Step_description__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take entity.
        /// </summary>
        public static string ___Take_entity__ {
            get {
                return ResourceManager.GetString("___Take_entity__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical piston.
        /// </summary>
        public static string ___Vertical_piston__ {
            get {
                return ResourceManager.GetString("___Vertical_piston__", resourceCulture);
            }
        }
    }
}
